# 主页面名字
alternate: Ukowu Shoka

# 是否显示页面加载动画 loading-cat
loader:
  start: false # 当初次打开页面时，显示加载动画
  switch: false # tab 切换到其他页面时，显示加载动画

#夜间模式
darkmode: true

# 再次打开的时候会滚动到上一次的界面
auto_scroll: # false

